### ISSUE TITLE
hotfix broke mod

### ISSUE THREAD

**Issue by votevent** [Krakenmeister/AoE2-Civbuilder#3]
yesterday's aoe2 hotfix broke the mod.

**Comment by Krakenmeister** [comment]
I see that there were an unusually large amount of request errors yesterday. Could you please elaborate on what you mean by "broke the mod"?

If the website request itself was breaking for you, the problem was either preexisting or there was something wrong with the .json file you uploaded (by manually editing it). If the mod you published just doesn't work anymore, creating the mod again with the same .json file(s) should solve your issue. If both of those worked fine but the new mod itself wasn't working in-game, then there is a serious problem caused by the hotfix that I have to address, but so far I haven't found anything of that sort.

Could you also try generating a random mod? That isolates the problem if it is caused by the hotfix.

Thank you for opening the issue and I look forward to hearing your results.
